version: '3'
services:
  database:
    container_name: ca-db
    image: 'mariadb:latest'
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  php:
    container_name: ca-php
    build:
      context: .
    volumes:
      - ./:/var/www/app
    depends_on:
      - database

  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
      - './public/:/var/www/app'
      - '.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - php